version: '2'

services:
  slim:
    image: php:7.2-alpine
    working_dir: /var/www
    entrypoint: php -S 0.0.0.0:80 -t public
    environment:
      docker: "true"
    ports:
      - 8090:80
    volumes:
      - ./application:/var/www
